import HomeHeader from '@/components/layout/HomeHeader'
import Footer from '@/components/layout/Footer'

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// }

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className='min-h-screen w-full relative bg-black'>
      {/* Ocean Abyss Background with Top Glow */}
      <div
        className='absolute inset-0 z-0'
        style={{
          background: 'radial-gradient(ellipse 80% 60% at 50% 0%, rgba(6, 182, 212, 0.25), transparent 70%), #000000'
        }}
      />
      <div className='relative flex flex-col min-h-screen'>
        <HomeHeader
          gradient
          items={[
            {
              title: 'Services',
              link: '/services/#services'
            }
          ]}
        />
        {/* <Header /> */}
        {children}
        <Footer />
      </div>
    </div>
  )
}
